services:
  backend:
    container_name: "${PROJECT_NAME}-backend"
    build:
      context: .
      args:
        DOCKER_PORT: ${DOCKER_PORT}
    env_file:
      - .env
    ports:
      - "${WEB_PORT}:${DOCKER_PORT}"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - app-network

  db:
    container_name: "${PROJECT_NAME}-db"
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Asia/Seoul
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - app-network

networks:
  app-network:
    name: ${PROJECT_NAME}-app-network

volumes:
  postgres_data:
    name: ${PROJECT_NAME}-postgres-data
